### ISSUE TITLE
Feature request: Replace legacy dependency for querystring parsing with URLSearchParams

### ISSUE THREAD

**Issue by spurreiter** [BackendStack21/0http#25]
IMHO there is no need to relay on the legacy querystring.parse method any longer, which is used in https://github.com/BackendStack21/0http/blob/master/lib/utils/queryparams.js .

Is there a chance to replace it with the native URLSearchParams?
Maybe this gives an additional performance boost?

E.g.
```js
module.exports = (req, url) => {
  const [path, search] = url.split('?')
  const searchParams = new URLSearchParams(search.replace(/\[\]=/g, '='))
  req.path = path
  req.query = Object.fromEntries(searchParams)
}
```

**Comment by jkyberneees** [comment]
Hi @spurreiter , thanks for contributing to this project.

You are totally right, it's time to upgrade the query string parsing support. Would you like to push the PR so this contribution is tracked? Otherwise, I am happy to take over. Let me know.

Thanks in advance

**Comment by spurreiter** [comment]
Hi @jkyberneees,
Thanks. Yes will create a PR.

**Comment by jkyberneees** [comment]
Feature was released in https://github.com/BackendStack21/0http/releases/tag/v3.4.0
