### ISSUE TITLE
String.prototype.replaceAll is supported in Node >= 15

### ISSUE THREAD

**Issue by sgurjeet** [BackendStack21/0http#27]
File: /lib/utils/queryparams.js
Line 3: new URLSearchParams(search.replaceAll('[]=', '='))

The string function 'replaceAll' is only supported in Node >= 15.
This is a breaking change which is causing everything to collapse

**Comment by jkyberneees** [comment]
Hi @sgurjeet, thanks for reporting. This issue is now fixed and Node.js v10.x is now used in our testing pipeline.
